import Config

config :worldloom, secure_cookies: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :worldloom, WorldloomWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :worldloom, WorldloomWeb.Endpoint,
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_proto]]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :logger_json, encoder: JSON

config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Basic,
     metadata: [:request_id, :source, :status, :attempt, :duration, :count]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
